# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_allpairs', [dirname(__file__)])
        except ImportError:
            import _allpairs
            return _allpairs
        if fp is not None:
            try:
                _mod = imp.load_module('_allpairs', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _allpairs = swig_import_helper()
    del swig_import_helper
else:
    import _allpairs
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class AllPairs(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AllPairs, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AllPairs, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _allpairs.new_AllPairs()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _allpairs.delete_AllPairs
    __del__ = lambda self : None;
    def FindAllSimilarPairs(self, *args): return _allpairs.AllPairs_FindAllSimilarPairs(self, *args)
    def SimilarPairsCount(self): return _allpairs.AllPairs_SimilarPairsCount(self)
    def CandidatesConsidered(self): return _allpairs.AllPairs_CandidatesConsidered(self)
    def IntersectionsPerformed(self): return _allpairs.AllPairs_IntersectionsPerformed(self)
AllPairs_swigregister = _allpairs.AllPairs_swigregister
AllPairs_swigregister(AllPairs)

class DataSourceIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataSourceIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataSourceIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["Get"] = lambda x: _allpairs.DataSourceIterator_Get
    if _newclass:Get = staticmethod(_allpairs.DataSourceIterator_Get)
    __swig_destroy__ = _allpairs.delete_DataSourceIterator
    __del__ = lambda self : None;
    def GetErrorMessage(self): return _allpairs.DataSourceIterator_GetErrorMessage(self)
    def Next(self, *args): return _allpairs.DataSourceIterator_Next(self, *args)
    def Seek(self, *args): return _allpairs.DataSourceIterator_Seek(self, *args)
    def Tell(self): return _allpairs.DataSourceIterator_Tell(self)
DataSourceIterator_swigregister = _allpairs.DataSourceIterator_swigregister
DataSourceIterator_swigregister(DataSourceIterator)

def DataSourceIterator_Get(*args):
  return _allpairs.DataSourceIterator_Get(*args)
DataSourceIterator_Get = _allpairs.DataSourceIterator_Get

# This file is compatible with both classic and new-style classes.


